### ISSUE TITLE
App Breaks when user tries to enter a value in a field while the previous field doesn't have a value

### ISSUE THREAD

**Issue by oyerohabib** [contigen/otp-input#1]
Hi @contigen, well done on this project. I was reading your [article](https://contigen.hashnode.dev/dont-entirely-trust-reacts-events), and came across this repo. It works fine when I act as a normal user, but as the app breaker or tester that I am, I discovered that the app breaks when I click on a particular input field and try to enter a value that doesn't have a value at the previous input field. An instance is when a user clicks on the 3rd input field and tries entereing a value while the previous input fields haven't been filled.

**Comment by contigen** [comment]
Hey @oyerohabib, thanks for reporting this, I'm surprised this issue exists because I remember particularly solving an edge case like this in dev. I'm guessing during refactoring  I deleted the wrong code or whatever; there'll be a fix soon 👍🏽

**Comment by contigen** [comment]
@oyerohabib, you can confirm the fix, thanks!

**Comment by oyerohabib** [comment]
@contigen well done on that. It workd fine now.
