### ISSUE TITLE
using the paste command ("command + V") on Mac doesn't work

### ISSUE THREAD

**Issue by oyerohabib** [contigen/otp-input#2]
Hi @contigen. I noticed the paste command doesn't work on Mac, I am not sure if it works on Windows though. However, I noticed when I used the paste option after right-clicking, that works fine.

**Comment by contigen** [comment]
Hey, I'm guessing something to do with some keys being default prevented, in hindsight it's probably a refactor side-effect thingy messing with the logic. Thanks, I'll look into it!
