### ISSUE TITLE
The next field value gets updated while user is currently on the previous field.

### ISSUE THREAD

**Issue by oyerohabib** [contigen/otp-input#3]
@contigen What happens here is that when the fields are filled and a user manually goes to a particular field and tries to enter a new value for it, what happens currently is that the value of the next fields gets updated with that value instead of the value of the particular field the user is on. This seems to be a bug.

**Comment by oyerohabib** [comment]
I tried something just now and discovered another bug. So, when the user uses the delete button, as I am using a Mac, not sure if it is the same experience on Windows, it correctly deletes the value of that particular field and then if the user enters a new value, the value is updated on the particular field and the next 2 fields gets updated with the particular value.

**Comment by contigen** [comment]
Hi! I verified the latter, it updates the focused field & updates the field two places from it. 
I'll check the code again, feel free to create PRs too

**Comment by contigen** [comment]
@oyerohabib, do you still experience the strange behaviour? I don't anymore

**Comment by contigen** [comment]
I'll close this now; if you experience any other strange behaviour, please open an issue.
